# Generated by Django 4.2.7 on 2024-04-11 16:23

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author", models.CharField(max_length=200)),
                ("title", models.CharField(max_length=150)),
                ("text", models.TextField(max_length=10000)),
                ("pub_date", models.DateTimeField(verbose_name="date published")),
            ],
        ),
    ]
