# Generated by Django 5.0.4 on 2024-04-13 10:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="article",
            old_name="title",
            new_name="heading",
        ),
        migrations.RemoveField(
            model_name="article",
            name="author",
        ),
        migrations.AddField(
            model_name="article",
            name="picture",
            field=models.ImageField(blank=True, upload_to="article_pictures/"),
        ),
        migrations.AddField(
            model_name="article",
            name="view_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="article",
            name="pub_date",
            field=models.DateTimeField(),
        ),
    ]
