# Generated by Django 5.0.4 on 2024-04-13 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0004_tags"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Tags",
            new_name="Tag",
        ),
        migrations.CreateModel(
            name="Article_Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "article_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="articles.article",
                    ),
                ),
                (
                    "tag_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="articles.tag"
                    ),
                ),
            ],
        ),
    ]
