# Generated by Django 5.0.4 on 2024-04-14 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0005_rename_tags_tag_article_tag"),
        ("authors", "0003_alter_author_name_author_articles"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="author",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="authors.author",
            ),
        ),
    ]
