# Generated by Django 5.0.4 on 2024-04-14 21:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authors", "0003_alter_author_name_author_articles"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="author_pictures/"
            ),
        ),
    ]
